import type { Recipe } from "./homestock";

// Assumed always available — excluded from missing count
export const CATALOG: Omit<Recipe, "id">[] = [
  {
    name: "Ginger Chicken Fried Rice",
    description: "Fast wok-fried rice with tender chicken, egg ribbons and a hit of fresh ginger.",
    difficulty: "Easy", time: "25 min", recipeType: "savory", tags: ["Quick", "Asian"],
    ingredients: ["cooked jasmine rice", "chicken breast, diced", "large eggs", "garlic cloves, minced",
      "fresh ginger, grated", "soy sauce", "sesame oil", "frozen peas & carrots", "spring onions, sliced"],
    steps: [
      "Heat oil in a wok over high heat and cook the diced chicken until golden, then set aside.",
      "Push rice into the wok and fry for 2–3 minutes, breaking up any clumps, until lightly toasted.",
      "Push rice to one side, crack in the eggs, scramble briefly, then fold through the rice.",
      "Add garlic, ginger, peas and carrots; stir-fry for 2 minutes until fragrant.",
      "Return the chicken, add soy sauce and sesame oil, and toss everything together for 1 minute.",
      "Scatter with spring onions and serve immediately.",
    ],
  },
  {
    name: "Wild Mushroom Risotto",
    description: "A slow, creamy risotto built on good stock, sautéed mushrooms and a generous finish of parmesan.",
    difficulty: "Medium", time: "40 min", recipeType: "savory", tags: ["Italian", "Vegetarian"],
    ingredients: ["arborio rice", "mixed mushrooms, sliced", "vegetable stock", "dry white wine",
      "shallots, minced", "garlic cloves, minced", "parmesan, grated", "butter", "thyme sprigs"],
    steps: [
      "Warm the stock in a separate pot and keep it at a gentle simmer.",
      "Sauté mushrooms in olive oil over high heat until browned; set aside.",
      "In the same pan, soften shallots and garlic in butter, then stir in the rice for 1 minute until glossy.",
      "Deglaze with white wine and stir until absorbed.",
      "Add warm stock a ladle at a time, stirring often, waiting for each addition to absorb before adding more, about 20 minutes.",
      "Fold in the mushrooms, parmesan and thyme; season and serve immediately.",
    ],
  },
  {
    name: "Rustic Tomato Basil Pasta",
    description: "A simple, punchy tomato sauce that comes together while the pasta water boils.",
    difficulty: "Easy", time: "20 min", recipeType: "savory", tags: ["Italian", "Quick", "Vegetarian"],
    ingredients: ["spaghetti", "crushed tomatoes", "garlic cloves, sliced", "fresh basil leaves",
      "parmesan, grated", "chili flakes"],
    steps: [
      "Bring a large pot of salted water to the boil and cook spaghetti until al dente.",
      "Warm olive oil in a pan and gently cook garlic and chili flakes until fragrant, not browned.",
      "Add crushed tomatoes, season, and simmer for 12 minutes, stirring occasionally.",
      "Tear in most of the basil and toss the drained pasta through the sauce with a splash of pasta water.",
      "Serve topped with parmesan and the remaining basil.",
    ],
  },
  {
    name: "Loaded Black Bean Tacos",
    description: "Smoky spiced black beans, crisp vegetables and avocado piled into warm tortillas.",
    difficulty: "Easy", time: "20 min", recipeType: "savory", tags: ["Mexican", "Vegetarian", "Quick"],
    ingredients: ["corn tortillas", "black beans, drained", "red bell pepper, diced", "red onion, diced",
      "avocado, sliced", "lime", "fresh cilantro, chopped", "cumin", "smoked paprika", "feta, crumbled"],
    steps: [
      "Warm black beans in a pan with cumin and smoked paprika, mashing lightly, for 5 minutes.",
      "Sauté bell pepper and onion until just softened, about 4 minutes.",
      "Warm the tortillas directly over a flame or in a dry pan until charred in spots.",
      "Fill tortillas with beans, peppers and onion.",
      "Top with avocado, feta and cilantro, and finish with a squeeze of lime.",
    ],
  },
  {
    name: "Thai Green Curry",
    description: "Fragrant coconut curry with tender chicken and vegetables, ready faster than takeout.",
    difficulty: "Medium", time: "35 min", recipeType: "savory", tags: ["Thai", "Asian"],
    ingredients: ["chicken thighs, sliced", "green curry paste", "coconut milk", "fish sauce",
      "brown sugar", "zucchini, sliced", "bell pepper, sliced", "Thai basil leaves", "jasmine rice"],
    steps: [
      "Fry the curry paste in a splash of oil over medium heat until fragrant, about 1 minute.",
      "Add the thicker part of the coconut milk and simmer until it splits slightly.",
      "Add chicken and cook, stirring, for 5 minutes.",
      "Pour in remaining coconut milk, fish sauce and brown sugar; simmer 10 minutes.",
      "Add zucchini and bell pepper, cook until just tender, about 6 minutes.",
      "Stir through Thai basil and serve over jasmine rice.",
    ],
  },
  {
    name: "Honey Garlic Glazed Salmon",
    description: "Sticky, caramelised salmon fillets with a fast three-ingredient glaze.",
    difficulty: "Easy", time: "25 min", recipeType: "savory", tags: ["Fish", "Quick"],
    ingredients: ["salmon fillets", "honey", "soy sauce", "garlic cloves, minced",
      "rice vinegar", "fresh ginger, grated", "sesame seeds", "spring onions, sliced"],
    steps: [
      "Whisk honey, soy sauce, garlic, ginger and rice vinegar together for the glaze.",
      "Sear salmon skin-side down in a hot pan for 4 minutes until crisp.",
      "Flip, pour over the glaze, and cook for 3–4 minutes, spooning the glaze over the fish as it thickens.",
      "Scatter with sesame seeds and spring onion before serving.",
    ],
  },
  {
    name: "Beef & Broccoli Stir-Fry",
    description: "Silky strips of beef and crisp broccoli in a glossy garlic-ginger sauce.",
    difficulty: "Easy", time: "20 min", recipeType: "savory", tags: ["Asian", "Quick"],
    ingredients: ["flank steak, thinly sliced", "broccoli florets", "garlic cloves, minced",
      "fresh ginger, grated", "soy sauce", "oyster sauce", "cornstarch", "brown sugar"],
    steps: [
      "Toss the beef with cornstarch and a splash of soy sauce; set aside for 10 minutes.",
      "Blanch broccoli in boiling water for 90 seconds, then drain.",
      "Sear beef in hot oil in batches until browned; set aside.",
      "Stir-fry garlic and ginger for 30 seconds, then return beef and broccoli to the pan.",
      "Add soy sauce, oyster sauce and brown sugar; toss until glossy and serve.",
    ],
  },
  {
    name: "Margherita Pizza",
    description: "A blistered, bubbling crust with San Marzano tomato, fresh mozzarella and basil.",
    difficulty: "Medium", time: "45 min", recipeType: "savory", tags: ["Italian"],
    ingredients: ["pizza dough", "crushed San Marzano tomatoes", "fresh mozzarella, torn",
      "fresh basil leaves"],
    steps: [
      "Preheat the oven with a pizza stone or upturned tray to its highest setting.",
      "Stretch the dough into a thin round on a floured surface.",
      "Spread crushed tomatoes evenly, leaving a border for the crust.",
      "Scatter torn mozzarella over the top and drizzle with olive oil.",
      "Bake for 8–10 minutes until the crust is blistered and the cheese is bubbling.",
      "Finish with fresh basil and a pinch of sea salt before slicing.",
    ],
  },
  {
    name: "Shakshuka with Feta",
    description: "Eggs gently poached in a spiced, bubbling tomato and pepper sauce.",
    difficulty: "Easy", time: "30 min", recipeType: "savory", tags: ["Middle Eastern", "Vegetarian", "Breakfast"],
    ingredients: ["onion, diced", "red bell pepper, diced", "garlic cloves, minced", "crushed tomatoes",
      "cumin", "smoked paprika", "chili flakes", "large eggs", "feta, crumbled", "fresh parsley, chopped"],
    steps: [
      "Sauté onion and bell pepper in olive oil until softened, about 6 minutes.",
      "Add garlic, cumin, smoked paprika and chili flakes; cook for 1 minute until fragrant.",
      "Pour in crushed tomatoes, season, and simmer for 12 minutes until thickened.",
      "Make small wells in the sauce and crack in the eggs.",
      "Cover and cook for 6–8 minutes until whites are set and yolks still soft.",
      "Scatter with feta and parsley, and serve straight from the pan.",
    ],
  },
  {
    name: "Brown Butter Banana Bread",
    description: "Deeply caramelised banana bread, moist in the middle with a toasty walnut crunch.",
    difficulty: "Easy", time: "65 min", recipeType: "sweet", tags: ["Baking", "Breakfast"],
    ingredients: ["ripe bananas, mashed", "unsalted butter", "brown sugar", "large eggs",
      "vanilla extract", "all-purpose flour", "baking soda", "walnuts, chopped"],
    steps: [
      "Melt butter in a light pan until it turns golden and smells nutty, then cool slightly.",
      "Whisk brown butter with brown sugar, eggs and vanilla until smooth.",
      "Fold in mashed banana, then gently fold in flour, baking soda and salt until just combined.",
      "Stir through the walnuts and pour into a greased loaf tin.",
      "Bake at 175°C (350°F) for 50–55 minutes until a skewer comes out clean.",
      "Cool in the tin for 10 minutes before turning out.",
    ],
  },
  {
    name: "Salted Brown Butter Chocolate Chip Cookies",
    description: "Crisp edges, a chewy centre, and deep caramel flavour from browned butter.",
    difficulty: "Easy", time: "25 min", recipeType: "sweet", tags: ["Baking", "Cookies"],
    ingredients: ["unsalted butter", "brown sugar", "granulated sugar", "large egg",
      "vanilla extract", "all-purpose flour", "baking soda", "dark chocolate, chopped"],
    steps: [
      "Brown the butter in a pan until nutty and golden, then cool for 10 minutes.",
      "Beat brown butter with both sugars, egg and vanilla until glossy.",
      "Fold in flour, baking soda and salt until just combined, then fold in chocolate.",
      "Chill the dough for at least 30 minutes.",
      "Scoop onto a lined tray and bake at 190°C (375°F) for 10–12 minutes.",
      "Sprinkle with flaky salt while still warm.",
    ],
  },
  {
    name: "Lemon Blueberry Ricotta Pancakes",
    description: "Extra-fluffy pancakes lifted with ricotta and bright lemon zest.",
    difficulty: "Easy", time: "20 min", recipeType: "sweet", tags: ["Breakfast", "Quick"],
    ingredients: ["all-purpose flour", "ricotta", "large eggs", "milk",
      "lemon, zested", "baking powder", "sugar", "fresh blueberries", "butter, for the pan"],
    steps: [
      "Whisk ricotta, eggs, milk and lemon zest together until smooth.",
      "Fold in flour, baking powder and sugar until just combined; do not overmix.",
      "Gently fold through most of the blueberries.",
      "Cook spoonfuls of batter in a buttered pan over medium heat for 2–3 minutes per side.",
      "Serve stacked with the remaining blueberries.",
    ],
  },
  {
    name: "Spiced Apple Cinnamon Oatmeal",
    description: "A warm five-minute breakfast bowl with soft cooked apple and toasted walnuts.",
    difficulty: "Easy", time: "12 min", recipeType: "sweet", tags: ["Breakfast", "Quick"],
    ingredients: ["rolled oats", "milk", "apple, diced", "cinnamon", "maple syrup", "walnuts, chopped"],
    steps: [
      "Bring milk to a gentle simmer in a small pot.",
      "Stir in oats, diced apple and cinnamon, and cook for 5 minutes, stirring often.",
      "Season with a pinch of salt and remove from the heat once creamy.",
      "Spoon into bowls, drizzle with maple syrup, and top with walnuts.",
    ],
  },
  {
    name: "Classic Tiramisu",
    description: "Espresso-soaked ladyfingers layered with a silky mascarpone cream.",
    difficulty: "Hard", time: "50 min", recipeType: "sweet", tags: ["Italian", "Dessert", "No-Bake"],
    ingredients: ["egg yolks", "sugar", "mascarpone", "heavy cream",
      "strong espresso, cooled", "ladyfinger biscuits", "cocoa powder", "dark rum"],
    steps: [
      "Whisk egg yolks and sugar over a warm water bath until pale and thickened.",
      "Off the heat, whisk in mascarpone until smooth.",
      "In a separate bowl, whip the cream to soft peaks and fold it through the mascarpone mixture.",
      "Combine espresso and rum; dip each ladyfinger briefly and layer in a dish.",
      "Spread half the cream over the biscuits, repeat with a second layer, then chill for at least 4 hours.",
      "Dust generously with cocoa powder just before serving.",
    ],
  },
];
